# Generated by Django 3.0.6 on 2020-06-04 04:52

from django.db import migrations, models
import totochicken.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=totochicken.models.upload_location)),
                ('price', models.IntegerField()),
                ('Info', models.TextField(max_length=500)),
            ],
        ),
    ]
